# Update Postman Collection
#
# This workflow runs in your Postman collection repository.
# It receives OpenAPI specs from service repos and updates collections.
#
# Add this file to: .github/workflows/update-collection.yml in your Postman repo

name: Update Postman Collection

on:
  repository_dispatch:
    types: [update-collection]
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name'
        required: true
      openapi_url:
        description: 'OpenAPI spec URL or local path'
        required: true

jobs:
  update-collection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Postman collection repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout sync tool
        uses: actions/checkout@v4
        with:
          repository: your-org/openapi-postman-sync  # Change this to your sync tool repo
          path: sync-tool

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: sync-tool/package-lock.json

      - name: Install dependencies
        working-directory: sync-tool
        run: npm ci

      - name: Determine service info
        id: service
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "service=${{ github.event.client_payload.service }}" >> $GITHUB_OUTPUT
            echo "ref=${{ github.event.client_payload.ref }}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.event.client_payload.sha }}" >> $GITHUB_OUTPUT
          else
            echo "service=${{ github.event.inputs.service }}" >> $GITHUB_OUTPUT
            echo "ref=manual" >> $GITHUB_OUTPUT
            echo "sha=manual" >> $GITHUB_OUTPUT
          fi

      - name: Download OpenAPI spec from artifact
        if: github.event_name == 'repository_dispatch'
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.POSTMAN_REPO_TOKEN }}
          run_id: ${{ github.event.client_payload.run_id }}
          name: openapi-spec
          path: ./specs
        continue-on-error: true

      - name: Fetch OpenAPI spec from URL (fallback)
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p specs
          curl -sSL "${{ github.event.inputs.openapi_url }}" -o specs/openapi.json

      - name: Convert OpenAPI to Postman
        run: |
          SERVICE="${{ steps.service.outputs.service }}"
          COLLECTION_FILE="collections/${SERVICE}.postman_collection.json"
          
          # Create collections directory if it doesn't exist
          mkdir -p collections
          
          # Convert OpenAPI to Postman
          node sync-tool/scripts/convert.js \
            --input specs/openapi.json \
            --output new-collection.json \
            --name "${SERVICE} API" \
            --folder-strategy tags
          
          # Check if existing collection exists
          if [ -f "$COLLECTION_FILE" ]; then
            echo "Existing collection found, merging..."
            node sync-tool/scripts/merge-collections.js \
              --new new-collection.json \
              --existing "$COLLECTION_FILE" \
              --output "$COLLECTION_FILE" \
              --preserve-tests \
              --preserve-prerequest \
              --verbose
          else
            echo "No existing collection, using new one"
            mv new-collection.json "$COLLECTION_FILE"
          fi
          
          # Cleanup
          rm -f new-collection.json

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore: update ${{ steps.service.outputs.service }} collection
            
            Updated from commit: ${{ steps.service.outputs.sha }}
            Source ref: ${{ steps.service.outputs.ref }}
          branch: auto-update/${{ steps.service.outputs.service }}
          delete-branch: true
          title: "🔄 Update ${{ steps.service.outputs.service }} Postman collection"
          body: |
            ## Automated Collection Update
            
            This PR was automatically generated by the OpenAPI to Postman sync workflow.
            
            ### Details
            - **Service**: ${{ steps.service.outputs.service }}
            - **Source Ref**: ${{ steps.service.outputs.ref }}
            - **Source Commit**: ${{ steps.service.outputs.sha }}
            
            ### Changes
            The collection has been updated based on the latest OpenAPI specification.
            Custom pre-request scripts and tests have been preserved.
            
            ---
            _This is an automated PR. Please review the changes before merging._
          labels: |
            automated
            postman-sync
          reviewers: |
            # Add reviewers here

      - name: Auto-merge if enabled
        if: steps.changes.outputs.changed == 'true'
        env:
          AUTO_MERGE: false  # Set to true to enable auto-merge
        run: |
          if [ "$AUTO_MERGE" = "true" ]; then
            echo "Auto-merge is enabled, merging PR..."
            gh pr merge --auto --squash
          fi
